language: python
python:
  - '3.6'

branches:
  only:
    'development'

install:
  - pip install -r requirements.txt

services:
  - postgresql


env: DJANGO_SETTINGS_MODULE=pur_beurre.settings.travis

script:
  - python manage.py test