language: python
python:
  - '3.6'

before_script:
  - pip install -r requirements.txt
  - psql -c 'create database travis_ci_test;' -U postgres
  - wget -P csv/ "https://fr.openfoodfacts.org/data/fr.openfoodfacts.org.products.csv"
services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=disquaire_project.settings.travis

script:
  - ./manage.py migrate
  - ./manage.py update_db