language: python
python:
  - '3.6'

branches:
  only:
    'development'

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

services:
  - postgresql


env: DJANGO_SETTINGS_MODULE=pur_beurre.settings.travis

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test