language: python
python:
  - '3.6'

before_script:
  - pip install -r requirements.txt

branches:
  only:
    'development'

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=pur_beurre.settings.travis

script:
  - ./manage.py test